# fly.toml app configuration file generated for motivameadow-back-end on 2024-03-06T12:16:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'motivameadow-back-end'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = "8080"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
